{
 "title": "My_node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Доступная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "mem_free{instance=\"localhost:8080\", job=\"my_node\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доступная память жесткого диска",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "disk_available{instance=\"localhost:8080\", job=\"my_node\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage{instance=\"localhost:8080\", job=\"my_node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}