{
 "title": "Overview",
 "time": { "from": "2024-01-10T00:32:31.177Z", "to": "2024-01-10T12:32:31.177Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Количество операций ввода/вывода",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"localhost:9100\", device=\"sda\"}[5m])",
     "legendFormat": "Количество операций"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"localhost:9100\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доступная память",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "Доступная память"
    }
   ]
  }
 ]
}